### PR TITLE
Allow Windows build

### PR DESCRIPTION
**Pull request by rcurtin**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Similar to #38, let's try to enable the Windows build!  I wonder what will happen.  (This is a long-long-long-term follow-up to #18.)

### CODE REVIEW

**Comment by rcurtin** [comment]
@conda-forge-admin, please rerender

**Comment by rcurtin** [comment]
@conda-forge-admin, please rerender

**Comment by rcurtin** [comment]
Holy crap, I can't believe it actually worked.  Now a final cleanup, and if it passes, I'm gonna merge it. :)

**Comment by rcurtin** [comment]
Incredible!  In it goes.

**Comment by jakirkham** [comment]
Nice work Ryan! 😄

**Comment by geekypathak21** [comment]
Great work @rcurtin

**Pull request merged**
